import type { HomeAssistant } from "./types";

const en = {
  settings: "Settings",
  close: "Close",
  off: "Off",
  apply: "Apply scene now",
  save: "Save",
  cancel: "Cancel",
  tree: "State tree",
  addRoot: "Add root",
  addChild: "Add child",
  remove: "Remove subtree",
  name: "Name",
  id: "ID",
  parent: "Parent",
  scene: "Scene",
  defaultChild: "Default child",
  occupied: "Is someone home?",
  inherit: "Inherit",
  yes: "Yes",
  no: "No",
  initial: "Initial state",
  roles: "Automation roles",
  overlays: "Overlays",
  addOverlay: "Add overlay",
  entities: "Entities",
  automation: "Automation",
  vacationConfirm: "Switch to vacation?",
  arrival: "Arrival",
  departure: "Departure",
  vacation: "Vacation",
  night: "Night",
  door: "Doors",
  gate: "Gates",
  person: "People",
  autoReturn: "Automatic return",
  autoAway: "Automatic away",
  grace: "Away grace (seconds)",
  schedule: "Night schedule",
  missing: "Entity not found",
  newState: "New state",
  newOverlay: "New overlay",
  automatic: "Automatic",
  heldUntil: "manual until",
  rule: "Activation",
  rules: {
    none: "Manual only",
    calendar: "Calendar",
    fixed: "Fixed dates",
    easter: "Easter",
    nth_weekday: "Weekday",
  },
  calendar: "Calendar",
  match: "Summary matches",
  from: "From (MM-DD)",
  to: "To (MM-DD)",
  fromDays: "From (days)",
  toDays: "To (days)",
  weekday: "Weekday",
  weekdays: {
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sun: "Sunday",
  },
  nth: "Which one",
  basis: "Counted from",
  anchorBasis: "A date",
  monthBasis: "A month",
  anchor: "Anchor (MM-DD)",
  month: "Month",
  days: "Length (days)",
  whenOccupied: "Only when",
  always: "Always",
  someoneHome: "Someone home",
  nobodyHome: "Nobody home",
  whenState: "Only in states",
  priority: "Priority",
  reason: {
    user: "changed manually",
    door: "door unlocked",
    gate: "gate opened",
    presence: "presence",
    schedule: "schedule",
    service: "service",
  },
  title: "House State",
  appearance: "Appearance",
  defaultAppearance: "Default",
  entityLabel: "House State entity",
  showOverlay: "Show overlay",
  confirmVacation: "Confirm vacation",
  fixedTime: "Fixed",
  solarTime: "Sun",
  time: "Time",
  event: "Event",
  sunset: "Sunset",
  sunrise: "Sunrise",
  offset: "Offset (seconds)",
  legacy: { state: "Legacy state", overlay: "Legacy overlay" },
  errorPrefix: "Could not update house state",
  entityRequired: "You must define an entity",
  matchPlaceholder: "^Christmas",
  durationDay: "d",
  durationHour: "h",
  durationMinute: "min",
  starterStates: {
    home: "Home",
    day: "Day",
    idle: "None",
    tv: "TV",
    eating: "Eating",
    night: "Night",
    away: "Away",
    vacation: "Vacation",
  },
  starterOverlays: {
    christmas: "Christmas",
    halloween: "Halloween",
    party: "Party",
  },
};
const nb: typeof en = {
  settings: "Innstillinger",
  close: "Lukk",
  off: "Av",
  apply: "Bruk scene nå",
  save: "Lagre",
  cancel: "Avbryt",
  tree: "Tilstandstre",
  addRoot: "Legg til rot",
  addChild: "Legg til barn",
  remove: "Fjern gren",
  name: "Navn",
  id: "ID",
  parent: "Forelder",
  scene: "Scene",
  defaultChild: "Standardbarn",
  occupied: "Er noen hjemme?",
  inherit: "Arv",
  yes: "Ja",
  no: "Nei",
  initial: "Starttilstand",
  roles: "Automatikkroller",
  overlays: "Overlegg",
  addOverlay: "Legg til overlegg",
  entities: "Entiteter",
  automation: "Automatikk",
  vacationConfirm: "Bytt til ferie?",
  arrival: "Hjemkomst",
  departure: "Avreise",
  vacation: "Ferie",
  night: "Natt",
  door: "Dører",
  gate: "Porter",
  person: "Personer",
  autoReturn: "Automatisk hjemkomst",
  autoAway: "Automatisk borte",
  grace: "Ventetid borte (sekunder)",
  schedule: "Nattplan",
  missing: "Fant ikke entiteten",
  newState: "Ny tilstand",
  newOverlay: "Nytt overlegg",
  automatic: "Automatisk",
  heldUntil: "manuelt til",
  rule: "Aktivering",
  rules: {
    none: "Kun manuelt",
    calendar: "Kalender",
    fixed: "Faste datoer",
    easter: "Påske",
    nth_weekday: "Ukedag",
  },
  calendar: "Kalender",
  match: "Tittel matcher",
  from: "Fra (MM-DD)",
  to: "Til (MM-DD)",
  fromDays: "Fra (dager)",
  toDays: "Til (dager)",
  weekday: "Ukedag",
  weekdays: {
    mon: "Mandag",
    tue: "Tirsdag",
    wed: "Onsdag",
    thu: "Torsdag",
    fri: "Fredag",
    sat: "Lørdag",
    sun: "Søndag",
  },
  nth: "Hvilken",
  basis: "Telles fra",
  anchorBasis: "En dato",
  monthBasis: "En måned",
  anchor: "Anker (MM-DD)",
  month: "Måned",
  days: "Lengde (dager)",
  whenOccupied: "Bare når",
  always: "Alltid",
  someoneHome: "Noen hjemme",
  nobodyHome: "Ingen hjemme",
  whenState: "Bare i tilstander",
  priority: "Prioritet",
  reason: {
    user: "endret manuelt",
    door: "låst opp dør",
    gate: "åpnet port",
    presence: "tilstedeværelse",
    schedule: "tidsplan",
    service: "tjeneste",
  },
  title: "Hustilstand",
  appearance: "Utseende",
  defaultAppearance: "Standard",
  entityLabel: "Hustilstandsentitet",
  showOverlay: "Vis overlegg",
  confirmVacation: "Bekreft ferie",
  fixedTime: "Fast tidspunkt",
  solarTime: "Solhendelse",
  time: "Klokkeslett",
  event: "Hendelse",
  sunset: "Solnedgang",
  sunrise: "Soloppgang",
  offset: "Forskyvning (sekunder)",
  legacy: { state: "Eldre tilstandsvelger", overlay: "Eldre overleggsvelger" },
  errorPrefix: "Kunne ikke oppdatere hustilstanden",
  entityRequired: "Du må angi en entitet",
  matchPlaceholder: "^jul",
  durationDay: "d",
  durationHour: "t",
  durationMinute: "min",
  starterStates: {
    home: "Hjemme",
    day: "Dag",
    idle: "Ingen",
    tv: "TV",
    eating: "Spiser",
    night: "Natt",
    away: "Borte",
    vacation: "Ferie",
  },
  starterOverlays: { christmas: "Jul", halloween: "Halloween", party: "Fest" },
};

/** UI language is independent of service tokens and the language of source code. */
export function language(
  hass?: Pick<HomeAssistant, "language" | "locale">,
): "nb" | "en" {
  const value = (hass?.language || hass?.locale?.language || "en")
    .toLowerCase()
    .replace(/_/g, "-");
  return /^(nb|no|nn)(-|$)/.test(value) ? "nb" : "en";
}
export function localize(
  hass?: Pick<HomeAssistant, "language" | "locale">,
): typeof en {
  return language(hass) === "nb" ? nb : en;
}
/** Only the integration's unmodified starter names are display translations. */
export function displayName(
  hass: HomeAssistant | undefined,
  item: { id: string; name: string },
  kind: "starterStates" | "starterOverlays",
): string {
  const defaults: Record<string, string> = en[kind];
  const translated: Record<string, string> = localize(hass)[kind];
  return defaults[item.id] === item.name ? translated[item.id] : item.name;
}
